default:
    tags:
      - asprunner
stages:
  - compile_pdf

compile_pdf:
  stage: compile_pdf
  image: aergus/latex
  script:
    - latexmk -pdf thk-example.tex
  artifacts:
    paths:
    - thk-example.pdf
